server:
  port: 8091
spring:
  datasource:
    url: jdbc:mysql://localhost:3306
    username: root
    password: your_password
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    defer-datasource-initialization: true
    show-sql: true
  sql:
    init:
      mode: always