CREATE DATABASE IF NOT EXISTS MAINDB;

USE MAINDB;

DROP TABLE IF EXISTS todo;

CREATE TABLE  todo (
    id INT PRIMARY KEY AUTO_INCREMENT,
    title VARCHAR(255) NOT NULL,
    description VARCHAR(255) NOT NULL
);